const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const state = { events: [], filter: 'all', user: null, location: { lat: 49.8397, lng: 24.0297 }, map: null, markerLayer: null, selectedMedia: null, authMode: 'login' };
const icons = { concert: '🎵', street: '🏙', sport: '⚽', other: '✨' };
async function api(url, options = {}) { const r = await fetch(url, { credentials:'include', ...options }); const data = r.status===204 ? null : await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.error||'REQUEST_FAILED'); return data; }
function toast(text){const e=document.createElement('div');e.className='toast';e.textContent=text;document.body.appendChild(e);setTimeout(()=>e.remove(),2600)}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initials(name='?'){return name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function initMap(){if(!window.L){$('#map').innerHTML='<div class="map-unavailable">Карта тимчасово недоступна. Стрічка подій і профіль залишаються доступними.</div>';return}state.map=L.map('map',{zoomControl:true}).setView([state.location.lat,state.location.lng],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(state.map);state.markerLayer=L.layerGroup().addTo(state.map);state.map.on('click',e=>{if($('#create').open)setLocation(e.latlng.lat,e.latlng.lng,'Вибрано на карті')})}
function markerIcon(category){return L.divIcon({className:'event-marker',html:`<span style="display:grid;place-items:center;width:38px;height:38px;border-radius:50% 50% 50% 8px;transform:rotate(-45deg);background:#ffd63d;border:3px solid white;box-shadow:0 5px 14px #0003"><b style="transform:rotate(45deg);font-size:16px">${icons[category]||'•'}</b></span>`,iconSize:[38,38],iconAnchor:[19,38]})}
function renderMarkers(){if(!state.markerLayer)return;state.markerLayer.clearLayers();state.events.forEach(e=>{const m=L.marker([e.latitude,e.longitude],{icon:markerIcon(e.category)}).addTo(state.markerLayer);m.on('click',()=>openEvent(e.id))})}
function mediaHtml(e,large=false){if(e.media_url&&e.media_type==='video')return `<video ${large?'controls':''} muted playsinline src="${escapeHtml(e.media_url)}"></video>`;if(e.media_url)return `<img src="${escapeHtml(e.media_url)}" alt="" loading="lazy">`;return `<div class="emoji-media">${icons[e.category]||'✨'}</div>`}
function renderFeed(){const q=$('#q').value.trim().toLowerCase();const list=state.events.filter(e=>(state.filter==='all'||e.category===state.filter)&&(!q||`${e.title} ${e.description} ${e.location_name||''}`.toLowerCase().includes(q)));$('#list').innerHTML=list.length?list.map(e=>`<article class="card" data-id="${e.id}"><div class="card-media">${mediaHtml(e)}</div><div class="card-body"><div class="author"><span class="avatar">${e.author_avatar?`<img class="avatar" src="${escapeHtml(e.author_avatar)}">`:initials(e.author_name)}</span><span>${escapeHtml(e.author_name||'Користувач')}</span><span class="verified">✓</span></div><h3>${escapeHtml(e.title)}</h3><div class="meta">⌖ ${escapeHtml(e.location_name||'Локація події')}<br>◷ ${new Date(e.created_at).toLocaleString('uk-UA',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</div><div class="going">${e.going_count||0} людей йдуть · <span class="verified">${e.trust_status==='verified'?'перевірено':'нова публікація'}</span></div></div></article>`).join(''):'<p class="meta">За цими параметрами подій не знайдено.</p>'}
async function loadEvents(){const p=new URLSearchParams({category:state.filter});const q=$('#q').value.trim();if(q)p.set('q',q);if(state.location){p.set('lat',state.location.lat);p.set('lng',state.location.lng);p.set('radius',50)}try{const d=await api(`/api/events?${p}`);state.events=d.events||[];renderFeed();renderMarkers()}catch{toast('Не вдалося завантажити події')}}
function openEvent(id){const e=state.events.find(x=>x.id===id);if(!e)return;$('#eventContent').innerHTML=`<div class="event-hero">${mediaHtml(e,true)}</div><div class="author"><span class="avatar">${e.author_avatar?`<img class="avatar" src="${escapeHtml(e.author_avatar)}">`:initials(e.author_name)}</span><b>${escapeHtml(e.author_name||'Користувач')}</b><span class="verified">✓ ${e.trust_status==='verified'?'довірений автор':'новий автор'}</span></div><h2 class="event-title">${escapeHtml(e.title)}</h2><p>${escapeHtml(e.description)}</p><div class="event-info">⌖ <b>${escapeHtml(e.location_name||'Точна локація')}</b><br>◷ Опубліковано ${new Date(e.created_at).toLocaleString('uk-UA')}<br>👥 <span id="goingCount">${e.going_count||0}</span> людей йдуть</div><div class="actions"><button class="going-btn" id="going">✓ Я йду</button><button class="decline-btn" id="decline">Відмовитись</button><button class="route-btn" id="route">➤ Прокласти маршрут</button></div><button class="report" id="report">⚑ Поскаржитися на фейк або спам</button>`;$('#event').showModal();$('#going').onclick=()=>attendance(e.id,'going');$('#decline').onclick=()=>attendance(e.id,'declined');$('#route').onclick=()=>window.open(`https://www.google.com/maps/dir/?api=1&destination=${e.latitude},${e.longitude}`,'_blank');$('#report').onclick=async()=>{if(!state.user)return openAuth();try{await api(`/api/events/${e.id}/report`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:'fake_or_spam'})});toast('Скаргу прийнято')}catch{toast('Скаргу вже подано або сталася помилка')}}}
async function attendance(id,status){if(!state.user)return openAuth();try{const d=await api(`/api/events/${id}/attendance`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const e=state.events.find(x=>x.id===id);if(e)e.going_count=d.going;$('#goingCount').textContent=d.going;renderFeed();toast(status==='going'?'Ти йдеш на подію ✓':'Статус змінено')}catch{toast('Потрібно увійти')}}
function setLocation(lat,lng,label='Геолокацію визначено'){state.location={lat,lng};$('#latitude').value=lat;$('#longitude').value=lng;$('#locationText').textContent=`${label} · ${lat.toFixed(5)}, ${lng.toFixed(5)}`;if(state.map)state.map.setView([lat,lng],15)}
function locateUser(showToast=true){if(!navigator.geolocation)return toast('Браузер не підтримує геолокацію');navigator.geolocation.getCurrentPosition(p=>{setLocation(p.coords.latitude,p.coords.longitude,'Моя локація');if(showToast)toast('Локацію визначено');loadEvents()},()=>toast('Дозвіл на геолокацію не надано'),{enableHighAccuracy:true,timeout:8000})}
function openAuth(mode='login'){state.authMode=mode;updateAuthMode();$('#auth').showModal()}
function updateAuthMode(){const reg=state.authMode==='register';$('#authTitle').textContent=reg?'Створити акаунт':'Увійти';$('#nameField').classList.toggle('hidden',!reg);$('#authSubmit').textContent=reg?'Зареєструватися':'Увійти';$$('.auth-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.authMode));$('#authPassword').autocomplete=reg?'new-password':'current-password';$('#authError').textContent=''}
async function authSubmit(e){e.preventDefault();const body={email:$('#authEmail').value,password:$('#authPassword').value};if(state.authMode==='register')body.name=$('#authName').value;try{const d=await api(state.authMode==='register'?'/api/auth/register':'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});state.user=d.user;$('#auth').close();toast(`Привіт, ${state.user.name}!`)}catch(err){$('#authError').textContent=err.message==='EMAIL_EXISTS'?'Такий email уже зареєстрований.':'Не вдалося виконати вхід. Перевір дані.'}}
function loadGoogle(){if(!window.APP_CONFIG.GOOGLE_CLIENT_ID)return;const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.onload=()=>{google.accounts.id.initialize({client_id:window.APP_CONFIG.GOOGLE_CLIENT_ID,callback:async response=>{try{const d=await api('/api/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credential:response.credential})});state.user=d.user;$('#auth').close();toast(`Привіт, ${state.user.name}!`)}catch{toast('Google-вхід не виконано')}}})};document.head.appendChild(s)}
function openCreate(){if(!state.user)return openAuth('login');$('#createForm').reset();$('#preview').classList.add('hidden');state.selectedMedia=null;$('#create').showModal();setLocation(state.location.lat,state.location.lng,'Моя локація');locateUser(false)}
async function publish(e){e.preventDefault();if(!state.user)return openAuth();const fd=new FormData();fd.append('title',$('#desc').value.trim().slice(0,80));fd.append('description',$('#desc').value.trim());fd.append('category',$('#cat').value);fd.append('latitude',$('#latitude').value);fd.append('longitude',$('#longitude').value);fd.append('location_name',$('#locationText').textContent);if(state.selectedMedia)fd.append('media',state.selectedMedia);try{await api('/api/events',{method:'POST',body:fd});$('#create').close();toast('Подію опубліковано ✓');await loadEvents()}catch{$('#createError').textContent='Не вдалося опублікувати. Перевір медіа та поля.'}}
function selectMedia(file){if(!file)return;state.selectedMedia=file;const url=URL.createObjectURL(file);$('#preview').classList.remove('hidden');$('#preview').innerHTML=file.type.startsWith('video/')?`<video controls src="${url}"></video>`:`<img src="${url}" alt="Попередній перегляд">`}
function openProfile(){if(!state.user)return openAuth();$('#profileContent').innerHTML=`<div class="profile-head"><div class="big-avatar">${state.user.avatar_url?`<img class="big-avatar" src="${escapeHtml(state.user.avatar_url)}">`:initials(state.user.name)}</div><div><h2>${escapeHtml(state.user.name)}</h2><p>${escapeHtml(state.user.email)}</p></div></div><div class="profile-actions"><button id="editProfile">✎ Змінити ім'я / аватар</button><button id="myLocation">⌖ Оновити мою локацію</button><button class="logout" id="logout">↪ Вийти з акаунта</button></div>`;$('#profile').showModal();$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});state.user=null;$('#profile').close();toast('Ви вийшли')};$('#myLocation').onclick=()=>locateUser();$('#editProfile').onclick=async()=>{const name=prompt('Нове ім’я',state.user.name);if(!name)return;try{const d=await api('/api/me',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});state.user=d.user;openProfile()}catch{toast('Не вдалося зберегти')}}}
$$('.x').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#q').oninput=()=>loadEvents();$('#chips').onclick=e=>{if(!e.target.dataset.c)return;state.filter=e.target.dataset.c;$$('#chips button').forEach(b=>b.classList.toggle('on',b===e.target));loadEvents()};$('#locate').onclick=()=>locateUser();$('#refresh').onclick=loadEvents;$('#mapnav').onclick=()=>document.querySelector('.map-section').scrollIntoView({behavior:'smooth'});$('#add').onclick=openCreate;$('#addnav').onclick=openCreate;$('#profileNav').onclick=openProfile;$('#bell').onclick=()=>toast(state.user?'Нових сповіщень поки немає':'Увійди, щоб отримувати сповіщення');$('#list').onclick=e=>{const c=e.target.closest('.card');if(c)openEvent(c.dataset.id)};$$('.auth-tabs button').forEach(b=>b.onclick=()=>{state.authMode=b.dataset.mode;updateAuthMode()});$('#authForm').onsubmit=authSubmit;$('#googleBtn').onclick=()=>{if(window.APP_CONFIG.GOOGLE_CLIENT_ID&&window.google?.accounts)google.accounts.id.prompt();else toast('Google-вхід буде доступний після додавання GOOGLE_CLIENT_ID')};$('#createForm').onsubmit=publish;$('#media').onchange=e=>selectMedia(e.target.files[0]);$('#galleryBtn').onclick=()=>{$('#media').removeAttribute('capture');$('#media').click()};$('#cameraBtn').onclick=()=>{$('#media').setAttribute('capture','environment');$('#media').click()};$('#pickLocation').onclick=()=>toast('Натисни потрібне місце на карті');
(async function boot(){initMap();loadGoogle();try{const d=await api('/api/me');state.user=d.user}catch{}loadEvents();try{const config=await api('/api/config');if(config.netlify){setInterval(loadEvents,30000);return}}catch{}const socket=window.io?.();socket?.on('event:created',()=>loadEvents());socket?.on('event:attendance',x=>{const e=state.events.find(e=>e.id===x.id);if(e){e.going_count=x.going;renderFeed()}})})();
